name: Test
on:
  push:
    branches:
      - main
      - dev-testing
permissions:
  contents: read

jobs:
  test:
    name: Firewall Tests 
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout action
        id: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name:  Run Firewall QA Tests
        uses: AikidoSec/firewall-tester-action@releases/v1
        with:
          dockerfile_path: ./Dockerfile
          skip_tests: test_allowed_ip,test_allowed_ip_for_wildcard_route,test_allowed_ip_most_restrictive,test_bypassed_ip_for_geo_blocking,test_user_rate_limiting_1_minute
          sleep_before_test: 15
          max_parallel_tests: 5